kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-springrest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springrest-app
  template:
    metadata:
      labels:
        app: springrest-app
    spec:
      containers:
        - name: my-springrest
          image: springrest-image:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"